<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
       <li class="level0 level-top ui-menu-item">
            <a href="<?php echo $this->getBaseUrl().""; ?>" class="level-top ui-corner-all"  role="menuitem">
                <span><?php echo __("Home")?></span>
            </a>
        </li>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>


        <li class="level0 level-top ui-menu-item">
            <a href="<?php echo $this->getBaseUrl()."recipes"; ?>" class="level-top ui-corner-all"  role="menuitem">
                <span><?php echo __("Recipes")?></span>
            </a>
        </li>

    </ul>
</nav>
